### PR TITLE
Fix Download button not updated

### LINKED ISSUE #8: BUG: Download button is not updated at the end of a game installation process
In the dowload.tsx component (`vertex_launcher/src/components/download.tsx`) the label is not updated when the corresponding game downloading process is completed. 

Current behavior: The button label is `Download` by default and switches to `Downloading...` when the button is clicked. When the download is done, the button label is not updated. If the page is reloaded, the button label switch to `Start`.

Wanted behavior: The button label is `Download` by default and switches to `Downloading...` when the button is clicked. When the download is done, the button label switches to `Start` automatically.

### PR DESCRIPTION
**Pull request by TxMat**
fixes #8

### CODE REVIEW

File: vertex_launcher/src-tauri/src/commands.rs [hunk 1]
```diff
@@ -226,6 +226,10 @@ pub async fn download(app_handle: tauri::AppHandle, game: u8) -> errors::Result<
             env::STORE_LOCAL_GAME_LIST_KEY,
             serde_json::to_value(&*game_list).unwrap(),
         );
+        app_handle.emit(
+            &format!("download_completed_{}", game),
+            serde_json::to_string(&game_list.get(&game).unwrap()).unwrap(),
+        )?;
```
Comment (GuicLuca) [inline vertex_launcher/src-tauri/src/commands.rs]: Duplicated events. Download complete event is already fired in the Download::complete function in `src-tauri/src/download.rs`.

File: vertex_launcher/src-tauri/src/commands.rs [hunk 2]
```diff
@@ -226,6 +226,10 @@ pub async fn download(app_handle: tauri::AppHandle, game: u8) -> errors::Result<
             env::STORE_LOCAL_GAME_LIST_KEY,
             serde_json::to_value(&*game_list).unwrap(),
         );
+        app_handle.emit(
+            &format!("download_completed_{}", game),
```
Comment (GuicLuca) [inline vertex_launcher/src-tauri/src/commands.rs]: Prefer using the constant event name from `src-tauri/src/env.rs` for better maintainability.
```suggestion
            &format!("{}_{}", env::CONST_EVENT_NAME_FROM_ENV, game),
```

File: vertex_launcher/src-tauri/src/commands.rs [hunk 3]
```diff
@@ -234,6 +238,22 @@ pub async fn download(app_handle: tauri::AppHandle, game: u8) -> errors::Result<
...
+            let game_json = serde_json::to_string(&game_data)?;
+            Ok(game_json)
+        }
+        None => Err(GameListFetchError(format!(
+            "Game with id {} not found",
+            game
+        ))),
+    }
+}
+
```
Comment (GuicLuca) [inline vertex_launcher/src-tauri/src/commands.rs]: Maybe put this function next to `get_game_list` (line 74) to keep related work together.

File: vertex_launcher/src-tauri/src/lib.rs [hunk 4]
```diff
@@ -99,7 +99,8 @@ pub fn run() {
         commands::get_launcher_version,
         commands::get_game_list,
         commands::download,
-        commands::launch
+        commands::launch,
+        commands::get_game
```
Comment (GuicLuca) [inline vertex_launcher/src-tauri/src/lib.rs]: Maybe add the command registration next to the registration of `get_game_list` (line 100) to keep related work together.

**Review by GuicLuca — CHANGES_REQUESTED** [review]
Excellent job done! Small details to fix, but will be merged after correction.

File: vertex_launcher/src-tauri/src/commands.rs (hunk 1 above)
Comment (GuicLuca) [reply vertex_launcher/src-tauri/src/commands.rs]: Remove the call in cmmands.rs to keep all the ends of the download process on the Download struct.

**Review by GuicLuca — APPROVED** [review]
lgtm
